<a href="https://colab.research.google.com/github/jyuurin/PI4_NumPy/blob/main/PI4_Ex2_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Ex 2 - NumPy
Importe os 2 arquivos e descubra a média de altura de quem nasceu entre 1998 e 2005.

Alunos: Felipe Fernandes e Julia Mendes

Bacharelado Ciência da Computação

PI 4 - Computação Cientifica

Prof.: Celso Crivelaro

In [ ]:
import numpy as np

In [8]:
# ler arquivos de altura e idade
arquivoAlturas = np.loadtxt('alturas.txt')
arquivoAnos = np.loadtxt('anos.txt')

In [9]:
# atribuir valores dos txts para uma variavel
arrayAlturas = np.array(arquivoAlturas, dtype=np.float16)
arrayAnos = np.array(arquivoAnos, dtype=int)

In [10]:
# testes
print(arrayAlturas[3], arrayAlturas[32], arrayAlturas[50])
print(arrayAnos[3], arrayAnos[32], arrayAnos[50])

1.947 1.852 1.898
1997 2009 1990

In [44]:
# Filtro de dados:

# Filtro de dados que satisfaz a logica do exercicio:  
filtrar = np.where((arrayAnos >= 1998) & (arrayAnos <= 2005))

# Transformar em um array
arrayIndiceFiltrado = np.array(filtrar, dtype=int)

# Tamanho do array
tamanhoArray = arrayIndiceFiltrado.size 

# Anos com base nos indices
arrayAnosFiltrado = arrayAnos[arrayIndiceFiltrado]

# Alturas com base nos indices
arrayAlturasFiltrado = arrayAlturas[arrayIndiceFiltrado]

# Soma de alturas
SomaAlturas = arrayAlturasFiltrado.sum()

In [46]:
print("DADOS ENCONTRADOS:\n")
print("\t- Numero de dados filtrados/Tamanho do Array: ", tamanhoArray)
print("\t- A soma das alturas: ", SomaAlturas)
print("\t- Media de alturas final: ", SomaAlturas / tamanhoArray)
print("\t- Media de alturas arredondada: ", round(SomaAlturas / tamanhoArray, 3))
print("__________________________________________________________________________")

print("Visualização de arrays filtrados: \n")

print("Array de indices filtrados: \n", arrayIndiceFiltrado)
print("__________________________________________________________________________")
print("Array de anos filtrados: \n", arrayAnosFiltrado)
print("__________________________________________________________________________")
print("Array de alturas filtradas: \n", arrayAlturasFiltrado)
print("__________________________________________________________________________")

DADOS ENCONTRADOS:

	- Numero de dados filtrados/Tamanho do Array:  390
	- A soma das alturas:  704.5
	- Media de alturas final:  1.8064102564102564
	- Media de alturas arredondada:  1.806
__________________________________________________________________________
Visualização de arrays filtrados:

Array de indices filtrados:
 [[  4   5   7  10  11  13  14  15  18  22  24  26  27  29  30  31  33  37
   38  39  41  43  44  47  51  54  58  59  60  62  66  68  69  71  74  76
   80  81  82  84  85  86  91  92  96 101 107 109 112 113 115 116 120 124
  126 127 132 133 135 137 138 140 141 143 146 147 149 150 152 153 156 158
  159 160 161 165 166 171 173 175 180 182 185 186 188 191 192 193 196 197
  199 202 204 205 209 216 221 222 223 224 226 228 229 230 235 236 238 242
  243 249 250 252 256 257 262 266 271 274 277 278 279 280 285 287 290 294
  295 302 303 310 311 314 316 318 320 322 323 325 329 330 331 333 335 340
  341 342 343 354 355 358 362 364 370 373 374 375 380 381 383 385 386 387
  388 389 390 391 395 400 401 402 404 410 411 415 418 426 427 428 429 431
  432 433 434 436 439 442 443 447 451 452 456 457 460 462 467 472 473 475
  476 478 481 484 485 490 491 492 495 500 503 504 510 511 514 517 519 529
  531 532 536 537 543 545 549 552 557 558 560 561 562 564 567 569 572 576
  577 585 587 588 592 593 596 597 602 603 606 607 612 618 619 622 623 632
  633 634 636 639 643 648 651 655 656 657 659 660 661 667 670 672 673 674
  676 680 682 683 685 687 688 689 690 691 692 693 695 698 699 701 711 712
  721 725 727 729 733 738 743 746 749 750 754 757 758 759 761 766 768 770
  771 774 776 778 779 780 781 783 790 791 792 795 796 797 800 802 808 811
  812 815 817 820 822 830 837 844 846 848 851 852 857 859 861 862 863 865
  869 872 874 875 876 884 887 888 891 893 895 897 904 905 910 914 915 916
  917 918 919 923 924 930 935 937 939 942 944 945 946 948 949 954 956 959
  960 961 962 965 971 972 977 980 981 985 988 995]]
__________________________________________________________________________
Array de anos filtrados:
 [[2005 1998 2005 2002 2001 2002 2004 2005 2004 2003 2004 1998 2002 2000
  2003 2004 2005 2002 2005 2000 2001 2002 2004 2003 2001 2003 1999 1998
  2004 2000 2004 1999 2001 2002 1998 2004 1999 1998 2003 2001 2001 1998
  2005 2003 2003 2005 1998 2000 2003 2004 2004 2002 2001 2003 2002 1999
  1999 2000 2003 2003 2002 1998 1998 2005 2002 2003 2003 2005 2005 2004
  2001 2004 2003 2005 1998 2001 2004 2004 2001 2004 1999 2000 2000 2004
  2004 1999 1999 1998 2001 2002 1998 1998 2001 2005 2004 2003 2005 2004
  2002 2000 1998 1998 2002 1999 2005 1998 2003 2005 2005 2005 2005 1999
  1999 2002 2004 2002 2001 1998 1998 2001 2001 2004 2000 2002 1999 1999
  2004 2000 2001 2003 2003 1999 2001 2001 1998 2001 2000 1999 2003 1998
  2005 1999 2004 2003 1999 2004 2003 2002 1999 2002 2002 2002 2004 2002
  2000 1999 2003 1998 1999 2005 2004 2000 2001 1999 2003 2001 2005 2000
  2004 2001 1998 2005 2002 2003 1998 1998 2002 1999 2003 1998 1999 2000
  2002 2003 2003 2002 2004 2002 2004 1999 2005 2004 1998 2003 2003 2000
  2003 2003 2004 2002 2004 1999 1998 2001 1999 2001 2000 2002 2004 1998
  2001 2003 2002 2000 1998 1998 1999 2002 1999 2002 2000 2000 1998 2002
  1998 2000 2001 1999 2000 2000 2004 2003 2005 2000 2001 2003 2002 2000
  1998 2001 2001 2001 2000 2004 2002 1999 2004 2001 2003 2003 1999 2003
  2005 2004 2004 2004 1998 1999 2001 1999 1999 1999 2005 2001 1998 2001
  2003 2003 1999 2000 2001 2002 2001 1998 2000 2002 2004 2003 2003 2002
  2003 2001 2001 2005 2004 2000 2002 1998 2001 2005 2004 1998 2003 2001
  2002 2005 1998 2005 2002 2003 1998 1998 1998 2000 2005 2001 2000 2002
  1998 2002 2000 2003 2002 2002 2002 2003 2003 2002 1999 2002 2002 1998
  1999 2005 2005 1999 2004 2002 1998 2000 2005 1999 1998 1998 1999 2005
  1999 2003 1998 1999 2002 2002 2003 2001 2003 2004 2001 1999 2000 2003
  2004 2003 1998 2000 2002 2001 1998 2001 2005 2004 2003 2000 2003 1998
  2005 2002 2000 2002 1998 2000 2001 1999 2005 2005 2000 2004 1998 1999
  2005 1999 1999 2001 1999 1998 1998 1998 1999 2001 2003 2005]]
__________________________________________________________________________
Array de alturas filtradas:
 [[1.725  1.959  1.974  1.671  1.989  1.825  1.73   1.871  1.965  1.64
  1.887  1.82   1.987  1.982  1.825  1.96   1.948  1.667  1.9    1.883
  1.732  1.622  1.675  1.794  1.975  1.679  1.834  1.7705 1.682  1.622
  1.693  1.87   1.802  1.899  1.829  1.887  1.777  1.757  1.943  1.652
  1.693  1.66   1.621  1.999  1.75   1.943  1.69   1.864  1.947  1.957
  1.723  1.989  1.818  1.735  1.778  1.923  1.872  1.737  1.936  1.797
  1.716  1.859  1.884  1.922  1.964  1.7    1.907  1.81   1.927  1.702
  1.979  1.897  1.8545 1.939  1.819  1.948  1.752  1.831  1.733  1.82
  1.789  1.602  1.898  1.718  1.9375 1.702  1.753  1.67   1.75   1.665
  1.765  1.771  1.987  1.8955 1.654  1.992  1.655  1.823  1.827  1.636
  1.979  1.612  1.681  1.888  1.893  1.628  1.897  1.931  1.901  1.786
  1.934  1.712  1.637  1.742  1.912  1.855  1.671  1.768  1.944  1.782
  1.834  1.719  1.67   1.964  1.957  1.74   1.9795 1.992  1.925  1.65
  1.645  1.633  1.868  1.908  1.905  1.919  1.906  1.803  1.648  1.893
  1.957  1.688  1.725  1.805  1.6455 1.957  1.761  1.711  1.756  1.825
  1.646  1.739  1.814  1.77   1.902  1.959  1.965  1.614  1.949  1.621
  1.746  1.914  1.841  1.921  1.899  1.666  1.998  1.609  1.904  1.987
  1.675  1.897  1.613  1.893  1.797  1.907  1.807  1.986  1.835  1.885
  1.896  1.838  1.84   1.655  1.618  1.894  1.942  1.894  1.6875 1.937
  1.652  1.945  1.741  1.756  1.699  1.854  1.949  1.677  1.802  1.767
  1.64   1.907  1.708  1.984  1.874  1.713  1.982  1.752  1.795  1.972
  1.815  1.893  1.836  1.843  1.837  1.807  1.619  1.684  1.682  1.784
  1.799  1.749  1.89   1.756  1.817  1.699  1.716  1.668  1.965  1.853
  1.972  1.779  1.898  1.649  1.973  1.657  1.752  1.816  1.977  1.983
  1.855  1.663  1.994  1.772  1.893  1.743  1.988  1.719  1.644  1.739
  1.993  1.791  1.838  1.8125 1.696  1.998  1.638  1.645  1.986  1.68
  1.742  1.976  1.842  1.924  1.656  1.896  1.985  1.71   1.887  1.628
  1.667  1.751  1.926  1.724  1.969  1.772  1.724  1.753  1.665  1.679
  1.946  1.754  1.828  1.701  1.841  1.732  1.882  1.669  1.664  1.924
  1.813  1.738  1.882  1.911  1.678  1.966  1.801  1.907  1.819  1.905
  1.929  1.747  1.642  1.797  1.769  1.907  1.649  1.947  1.954  1.715
  1.837  1.847  1.762  1.889  1.732  1.864  1.75   1.946  1.816  1.703
  1.64   1.617  1.768  1.972  1.681  1.949  1.704  1.72   1.62   1.709
  1.622  1.848  1.73   1.609  1.66   1.865  1.636  1.86   1.833  1.713
  1.921  1.885  1.794  1.786  1.728  1.673  1.928  1.978  1.639  1.615
  1.828  1.935  1.897  1.816  1.891  1.999  1.625  1.755  1.734  1.754
  1.74   1.889  1.739  1.938  1.75   1.64   1.997  1.965  1.901  1.955
  1.93   1.804  1.938  1.613  1.74   1.967  1.891  1.826  1.764  1.797
  1.634  1.768  1.693  1.728  1.698  1.602  1.793  1.887  1.665  1.6   ]]
__________________________________________________________________________